apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sensors-gas-station-factory-1
  labels:
    strimzi.io/cluster: my-cluster
  namespace: gas-station-infra
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3
